### ISSUE TITLE
phase encoder options

### ISSUE THREAD

**Issue by cooperrc** [imkishan96/Inverted_Pendulum#1]
Thanks for sharing these resources! I wanted to build my own version, but the LPD3806 is tough to find online. 

What are some other optical rotary encoders that would make suitable substitutes?

- [x] [H38S600B](https://www.newegg.com/p/286-000J-00004) ?
- [ ] anything else?

**Comment by imkishan96** [comment]
H38S600B will work.
You can use any incremental encoder as long as you are willing to make some changes to the Arduino CAN_send code to adjust for pulse per revolution and CAD model to adapt to that encoder.

**Comment by cooperrc** [comment]
> H38S600B will work.
> You can use any incremental encoder as long as you are willing to make some changes to the Arduino CAN_send code to adjust for pulse per revolution and CAD model to adapt to that encoder.

Excellent, I'll give it a shot. If there are other issues I may reach out again.

**Comment by imkishan96** [comment]
for sure.
